[versions]

coroutines = "1.7.3"
junit = "5.10.1"
jvm = "17"
kotlin = "1.9.21"
mockk = "1.13.8"
spotless = "6.23.0"

[libraries]

# Kotlin
kotlin_core = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlinx_coroutines_core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx_coroutines_test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Tests
junit = { module = "org.junit.jupiter:junit-jupiter" }
junit_bom = { module = "org.junit:junit-bom", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[bundles]

kotlin_all = [
    "kotlin_core",
    "kotlinx_coroutines_core",
    "kotlinx_coroutines_test"
]

tests_all = [
    "junit",
    "mockk"
]
